# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=100, verbose_name='object_id')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBN')),
                ('curator', models.CharField(max_length=200, verbose_name='Curador')),
                ('edition', models.CharField(max_length=100, verbose_name='Edição')),
                ('pages', models.IntegerField(default=1, verbose_name='Número de páginas')),
                ('num_ratings', models.IntegerField(default=1)),
                ('total_ratings', models.IntegerField(default=1)),
                ('blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['name', 'author'],
            },
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('File', 'Arquivo'), (None, 'Selecione um tipo')], max_length=20)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('url', models.TextField(verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Cover',
                'verbose_name_plural': 'Covers',
                'ordering': ['name', 'url'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='cover_file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.Cover', verbose_name='Cover'),
        ),
    ]
