# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name', 'author'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='cover',
            options={'ordering': ['name', 'url'], 'verbose_name': 'Cover', 'verbose_name_plural': 'Covers'},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='cover_file',
        ),
        migrations.AlterField(
            model_name='cover',
            name='type',
            field=models.CharField(choices=[('File', 'Arquivo'), (None, 'Selecione um tipo')], max_length=20),
        ),
    ]
